### ISSUE TITLE
Discussion: Expected performance for gba platform

### ISSUE THREAD

**Issue by rajsite** [asiekierka/wasm4-aot#3]
## Overview

I converted a few examples from wasm-4:
https://wasm4.org/play/corn
https://wasm4.org/play/racer
https://wasm4.org/play/snake

To target the gba platform:
[converted.zip](https://github.com/asiekierka/wasm4-aot/files/10098927/converted.zip)

And it doesn't look like those examples are able to run at full speed in several of the gba emulators I tried:
gbajs 2 ([online](https://andychase.me/gbajs2/)) ([source](https://github.com/andychase/gbajs2))
wgpa ([online](https://web-gba.vercel.app/)) ([source](https://github.com/pokemium/wgba))

Observed behavior:
- racer doesn't seem to get passed the loading screen
- corn and snake seem to run (guessing visually) at ~20% of the speed of the game on wasm4.org

Snake from wasm4 site:

![snakewasm4](https://user-images.githubusercontent.com/1588923/204153437-e7f7052c-8890-401c-ab7a-b94b5aaaba8f.gif)

Snake after conversion to gba rom:

![snakegba](https://user-images.githubusercontent.com/1588923/204153447-1b709b75-bddc-4e75-8f78-659b1aac9d60.gif)

## Context 

My ultimate goal is to run the gba rom on the [funkey s](https://www.funkey-project.com/) and I haven't tried the above gba roms on the device yet but the performance of the roms in several different gba emulators makes me expect it will run similar to the above.

## Question
- Is the performance difference observed for the gba roms expected?
- Any ideas for how to improve performance? Looks like if I run an emulator like visual boy advance at ~400% the games run closer to the expected speed.

**Comment by asiekierka** [comment]
>Is the performance difference observed for the gba roms expected?

Yes. We're talking a 16MHz ARM chip trying to draw a 128x128 bitmapped game (so not benefitting from hardware graphics acceleration) at 60FPS.

>Any ideas for how to improve performance?

Port WASM-4 games or a WASM-4 runtime to the FunKey-S directly.

**Comment by rajsite** [comment]
Makes sense! Thanks for sharing the project, it's pretty darn cool! 😄

**Comment by asiekierka** [comment]
Thank you for the kind words.
